language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - tools
  - build-tools-27.0.3
  - android-26
  - android-27
  - extra-android-m2repository
  - extra-android-support
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- openssl aes-256-cbc -K $encrypted_db335fe3f5d5_key -iv $encrypted_db335fe3f5d5_iv
  -in keystore.jks.enc -out keystore.jks -d
- chmod +x gradlew
script:
- "./gradlew assembleRelease"
deploy:
  provider: releases
  api_key:
    secure: $api_key
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true
